# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 06:30
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.TextField(default='https://www.flickr.com', validators=[django.core.validators.URLValidator()]),
            preserve_default=False,
        ),
    ]
