# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_joined', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=64)),
            ],
        ),
        migrations.RemoveField(
            model_name='friends',
            name='created',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='friend',
        ),
        migrations.AddField(
            model_name='friendship',
            name='friends',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Friends'),
        ),
        migrations.AddField(
            model_name='friendship',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.User'),
        ),
        migrations.AddField(
            model_name='friends',
            name='members',
            field=models.ManyToManyField(through='users.Friendship', to='users.User'),
        ),
    ]
