# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-03 05:26
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('description', models.TextField()),
                ('longitude', models.CharField(max_length=255)),
                ('latitude', models.CharField(max_length=255)),
                ('picture', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('host', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='for_host', to='users.User')),
            ],
        ),
    ]
